image: gitpod/workspace-full

# Commands that will run on workspace start
tasks:
    - name: Setup, Install & Build
      init: pnpm install
      command: pnpm run run:ts

# Ports to expose on workspace startup
ports:
    - port: 1235
      onOpen: open-preview
      name: Presentation
      description: Presentation Preview
      visibility: private
      protocol: https
